version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resize021"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4mjiayxci6nh"
s3_prefix = "resize012"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EEAssetsBucket=\"cf-templates-1xnac3rwgtxo7-us-west-2\" EEAssetsKeyPrefix=\"data/\" EBSVolumeSize=\"25\" PolicyArn=\"NONE\" UserDataScript=\"userdata.sh\""

